## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore SIDB SPFILE VARCHAR nindent sqlplus sysdba tablespace tblspace

{{- if .Values.database }}
{{- if eq .Values.database.type "SIDB-FREE" }}
{{- $pdbName = "FREEPDB1" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-custom-scripts
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  init.sh: |
    sqlplus <<- EOF
    connect / as sysdba
    ALTER SYSTEM SET VECTOR_MEMORY_SIZE=512M SCOPE=SPFILE;
    ALTER SESSION SET CONTAINER={{- $pdbName }};
    DECLARE
      l_conn_user VARCHAR2(255);
      l_user      VARCHAR2(255);
      l_tblspace  VARCHAR2(255);
    BEGIN
      BEGIN
          SELECT user INTO l_conn_user FROM DUAL;
          SELECT username INTO l_user FROM DBA_USERS WHERE USERNAME='AI_OPTIMIZER';
      EXCEPTION WHEN no_data_found THEN
          EXECUTE IMMEDIATE 'CREATE USER "AI_OPTIMIZER" IDENTIFIED BY "${ORACLE_PWD}"';
      END;
      SELECT default_tablespace INTO l_tblspace FROM dba_users WHERE username = 'AI_OPTIMIZER';
      EXECUTE IMMEDIATE 'ALTER USER "AI_OPTIMIZER" QUOTA UNLIMITED ON ' || l_tblspace;
      EXECUTE IMMEDIATE 'GRANT DB_DEVELOPER_ROLE TO "AI_OPTIMIZER"';
      EXECUTE IMMEDIATE 'ALTER USER "AI_OPTIMIZER" DEFAULT ROLE ALL';
    END;
    /
    STARTUP FORCE;
    ALTER SYSTEM REGISTER;
    EOF
{{- else if .Values.oci_config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release.name" . }}-oci-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- with .Values.oci_config }}
    {{- if .tenancy }}
  tenancy: {{ .tenancy | quote }}
    {{- end }}
    {{- if .user }}
  user: {{ .user | quote }}
    {{- end }}
    {{- if .fingerprint }}
  fingerprint: {{ .fingerprint | quote }}
    {{- end }}
    {{- if .region }}
  region: {{ .region | quote }}
    {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}