## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent tolerations ollama

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    "app.kubernetes.io/component": "api"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      "app.kubernetes.io/component": "api"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        "app.kubernetes.io/component": "api"
    spec:
      securityContext:
        fsGroup: 10001
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          env:
            - name: API_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.apiSecretName" . }}
                  key: {{ include "app.apiSecretKey" . }}
            {{- if (default false .Values.oci_config.oke) }}
            - name: OCI_CLI_REGION
              value: {{ .Values.oci_config.region }}
            - name: OCI_CLI_AUTH
              value: "oke_workload_identity"
            {{- end }}
            {{- if .Values.database }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "databaseSecret" . }}
                  key: {{ default "username" (get (default dict .Values.database.authN) "usernameKey") }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "databaseSecret" . }}
                  key: {{ default "password" (get (default dict .Values.database.authN) "passwordKey") }}
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "databaseSecret" . }}
                  key: {{ default "service" (get (default dict .Values.database.authN) "serviceKey") }}
              {{- if eq .Values.database.type "ADB-S" }}
            - name: DB_WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "release.name" . }}-adb-wallet-pass-{{ .Release.Revision }}
                  key: {{ include "release.name" . }}-adb-wallet-pass-{{ .Release.Revision }}
              {{- end }}             
            {{- end }}
            {{- if $.Values.global.enableOllama }}
            - name: ON_PREM_OLLAMA_URL
              value: {{ include "ollama.serviceUrl" $ }}
            {{- end }}
            {{- with .Values.models }}
              {{- $models := . }}
              {{- $envMap := dict "openAI" "OPENAI_API_KEY" "perplexity" "PPLX_API_KEY" "cohere" "COHERE_API_KEY" }}
              {{- range $key, $envName := $envMap }}
                {{- with index $models $key }}
                  {{- if .secretName }}
            - name: {{ $envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey | default "apiKey" }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          ports:
            - name: server-port
              containerPort: 8000
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ include "getPath" . }}v1/liveness
              port: server-port
            {{- with omit .Values.livenessProbe "enabled" }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ include "getPath" . }}v1/readiness
              port: server-port
            {{- with omit .Values.readinessProbe "enabled" }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: "/app/tmp"
            {{- if and (hasKey .Values "database") (eq (default "" .Values.database.type) "ADB-S") }}
            - name: tns-admin
              mountPath: /app/tns_admin
            {{- end }}
            {{- if and .Values.oci_config .Values.oci_config.fileSecretName }}
            - name: oci-config
              mountPath: "/app/runtime/.oci"
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if and (hasKey .Values "database") (eq (default "" .Values.database.type) "ADB-S") }}
        - name: tns-admin
          secret:
            secretName: {{ include "release.name" . }}-adb-tns-admin-{{ .Release.Revision }}
        {{- end }}        
        {{- if and .Values.oci_config .Values.oci_config.fileSecretName }}
        - name: oci-config
          secret:
            secretName: {{ .Values.oci_config.fileSecretName | quote }}
            optional: true
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}