## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore FREEPDB

{{- if .Values.database }}
  {{- $root := . }}

  {{- $secretName := include "databaseSecret" . }}
  {{- $secret_existing := lookup "v1" "Secret" $root.Release.Namespace $secretName }}

  {{- if not $secret_existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  username: "AI_OPTIMIZER"
  password: "{{ include "randomPassword" . }}"
  service: "{{ include "release.name" . }}-db-1521:1521/FREEPDB1"
---
  {{- end }}

  {{- if eq .Values.database.type "ADB-S" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release.name" . }}-adb-wallet-pass-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
stringData:
  {{ include "release.name" . }}-adb-wallet-pass-{{ .Release.Revision }}: {{ randAlphaNum 16 | quote }}
  {{- end}}
  
{{- end }}