## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.serviceName" . }}
  labels: 
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector: 
    {{- include "app.selectorLabels" . | nindent 4 }}