## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
[global]
disableWidgetStateDuplicationWarning = true

[theme]
font = "sans-serif-pro"
headingFont = "sans-serif"
codeFont = "monospace"

[theme.sidebar]
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
cookieSecret = "oaie-client-cookie"
headless = true

[client]
toolbarMode = "minimal"