## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
{{- if or (not (hasKey .Values.global.api "secretName")) (eq .Values.global.api.secretName "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release.name" . }}-api-key
  labels: 
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.global.api.apiKey | b64enc }}
{{ end }}