## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

{{ include "apiKeyOrSecretName.required" . }}

{{- if .Values.global.api.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.apiSecretName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  "{{ include "app.apiSecretKey" . }}": "{{ .Values.global.api.apiKey | b64enc }}"
{{- end }}