## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

{{- if .Values.server.database }}
  {{- if eq .Values.server.database.type "ADB-S" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-adb-wallet-pass-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/component: database
    {{- include "global.labels" . | nindent 4 }}
stringData:
  {{ .Release.Name }}-adb-wallet-pass-{{ .Release.Revision }}: {{ include "server.randomPassword" . | quote }}
  {{ end -}}
{{ end -}}