## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

{{- if .Values.server.database }}
  {{- if eq .Values.server.database.type "ADB-S" }}
apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: {{ .Release.Name }}-adb-s
  labels:
    app.kubernetes.io/component: database
    {{- include "global.labels" . | nindent 4 }}
spec:
  action: "Sync"
  details:
    id: {{ .Values.server.database.oci_db.ocid }}
  wallet:
    name: {{ .Release.Name }}-adb-tns-admin-{{ .Release.Revision }}
    password:
      k8sSecret:
        name: {{ .Release.Name }}-adb-wallet-pass-{{ .Release.Revision }}
    {{- if .Values.server.oci_config }}
  ociConfig:
    configMapName: {{ .Release.Name }}-oci-config
      {{- if .Values.server.oci_config.keySecretName }}
    secretName: {{ .Values.server.oci_config.keySecretName }}
      {{ end -}}
    {{ end -}}
  {{ end -}}
{{ end -}}
