## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.serviceName" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "global.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/component: server
    {{- include "global.selectorLabels" . | nindent 4 }}
