# Copyright (c) 2024, 2025, Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl
# spell-checker: disable

global:
  api:
    secretName: "${label}-api-key"
  enableClient: true
  enableOllama: ${k8s_node_pool_gpu_deploy}

# -- API Server configuration
server:
  enabled: true
  image:
    repository: ${repository_server}
    tag: "latest"
  imagePullPolicy: Always

  ingress:
    enabled: true
    className: native-ic
    annotations:
      nginx.ingress.kubernetes.io/upstream-vhost: "${lb_ip}"
      oci-native-ingress.oraclecloud.com/http-listener-port: "8000"
      oci-native-ingress.oraclecloud.com/protocol: TCP

  service:
    http:
      type: "NodePort"

  # -- Enable Workload Identity
  oci_config:
    oke: true
    region: "${oci_region}"

  # -- Oracle Autonomous Database Configuration
  database:
    type: "ADB-S"
    ocid: "${adb_ocid}"      
    authN:
      secretName: "${adb_name}-authn"

client:
  image:
    repository: ${repository_client}
    tag: "latest"
  imagePullPolicy: Always

  ingress:
    enabled: true
    className: native-ic
    annotations:
      nginx.ingress.kubernetes.io/upstream-vhost: "${lb_ip}"
      oci-native-ingress.oraclecloud.com/http-listener-port: "80"
      oci-native-ingress.oraclecloud.com/protocol: TCP

  service:
    http:
      type: "NodePort"

  features:
    disableTestbed: "false"
    disableApi: "false"
    disableTools: "false"
    disableDbCfg: "false"
    disableModelCfg: "false"
    disableOciCfg: "false"
    disableSettings: "false"

ollama:
  models:
    enabled: true
    modelPullList:
      - llama3.1
      - mxbai-embed-large
  resources:
    limits:
      nvidia.com/gpu: 1
