global:
  enableOllama: false
server:
  replicaCount: 1
  image:
    repository: localhost/ai-optimizer-server
    tag: latest
  database:
    type: "ADB-FREE"
    image:
      repository: container-registry.oracle.com/database/adb-free
      tag: latest-23ai
  # oci_config:
  #   fileSecretName: "oci-config-file"
client:
  replicaCount: 1
  image:
    repository: localhost/ai-optimizer-client
    tag: latest
ollama:
  replicaCount: 1
  models:
    enabled: true