## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore

# replicaCount: number of desired pod replicas for the Deployment when autoscaling is disabled
replicaCount: 1

# autoscaling: HPA when enabled, requires metrics-server to be installed
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# imagePullSecrets: Secret name containing image pull secrets
imagePullSecrets: []
  # - name: registry_cred

# image: image and tag to pull incl policy
image:
  repository: localhost/ai-optimizer-server
  tag: latest
imagePullPolicy: IfNotPresent

# service: type of Kubernetes service to expose the HTTP port.
service:
  http:
    type: "ClusterIP"

# ingress: controls the Ingress resource to expose the service.
ingress:
  enabled: false
  className: nginx # IngressClass name (e.g., "nginx" for NGINX ingress controller)
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/upstream-vhost: "localhost"
  tls: []
    # - hosts:
    #     - example.com
    #   secretName: example-tls

# database: Oracle Database Configuration, many different options
# review the documentation for more details; use the OraOperator 
database:
  ## SIDB Containerized Example
  # type: "SIDB-FREE"
  # image:
  #   repository: container-registry.oracle.com/database/free
  #   tag: latest
  ## ADB Containerized Example (not implemented)
  # type: "ADB-FREE"
  # image:
  #   repository: container-registry.oracle.com/database/adb-free
  #   tag: latest-23ai
  ## OCI ADB-S Workload Principle Example (requires OraOperator)
  # type: "ADB-S"
  # ocid: "ocid1.autonomousdatabase.oc1..."
  # authN:
  #   secretName: "db-authn"

# oci_config: Oracle Cloud Infrastructure configurations
oci_config:
  # oke: will enable workload identity principals (must be implemented)
  oke: false
  tenancy: ""
  user: ""
  fingerprint: ""
  region: ""
  # fileSecretName: containing a config file and the key_file(s)
  # use the scripts/oci_config.py script to help create the secret
  fileSecretName: ""
  # privateKeySecret: single API key corresponding to above parameters
  # used by OraOperator when not OKE
  privateKeySecret:

# models: specify secretName and secretKey to enable 3rd-Party Models
models:
  openAI:
    # secretName: "openai-secret"
    # secretKey: ""       # Optional, defaults to "apiKey" if not specified
  perplexity:
    # secretName: "perplexity-secret"
    # # secretKey omitted, will default to "apiKey"
  cohere:
    # secretName: "cohere-secret"
    # secretKey: "customKeyName"  # Example of overriding the default key

# livenessProbe: defines settings for the liveness probe.
# Set `enabled` to false to disable the probe entirely.
livenessProbe:
  enabled: true
  initialDelaySeconds: 10       # Time (in seconds) to wait before starting the probe
  periodSeconds: 30             # Time (in seconds) between probe checks
  timeoutSeconds: 30            # Time (in seconds) to wait for probe response
  failureThreshold: 10          # Number of failures before marking the container as unhealthy
  successThreshold: 1           # Number of successes required to consider the container healthy

# readinessProbe: defines settings for the liveness probe.
# Set `enabled` to false to disable the probe entirely.
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 15
  failureThreshold: 10
  successThreshold: 1 

# volumes: user defined additional volumes
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# volumeMounts:  user defined additional volumeMounts
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# podLabels: additional key:value labels to add to pods
podLabels: {}
  # environment: "production"
  # team: "devops"

# podAnnotations: additional key:value annotations to add to the Pod template metadata
podAnnotations: {}
  # prometheus.io/scrape: "true"
  # prometheus.io/port: "9102"

# resources: requests and limits for the container
# Recommended not to specify default resources and to leave this as a conscious choice for the user.
# This also increases chances charts run on environments with little resources, such as Kind. 
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# nodeSelector: to constrain pods to specific nodes
nodeSelector: {}
  # disktype: ssd

# affinity: rules for scheduling pods
affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #           - key: app
  #             operator: In
  #             values:
  #               - my-app
  #       topologyKey: "kubernetes.io/hostname"

# tolerations: for scheduling pods on tainted nodes
tolerations: []
  # - key: "key1"
  #   operator: "Exists"
  #   effect: "NoSchedule"