## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

{{- if .Values.client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "global.fullname" . }}-client-http
  labels:
    app.kubernetes.io/component: client
    {{- include "global.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  selector:
    app.kubernetes.io/component: client
    {{- include "global.selectorLabels" . | nindent 4 }}
{{ end -}}