## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v2
name: ai-optimizer
description: A Helm chart Oracle AI Optimizer and Toolkit
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://github.com/oracle-samples/ai-optimizer/blob/main/src/client/media/logo.png
maintainers:
  - name: Oracle
    email: obaas_ww@oracle.com
    url: https://github.com/oracle-samples/ai-optimizer

dependencies:
  - name: server
    version: 1.0.0
    repository: file://charts/server
    condition: server.enabled
  - name: client
    version: 1.0.0
    repository: file://charts/client
    condition: client.enabled
  - name: ollama
    version: 1.0.0
    repository: file://charts/ollama
    condition: ollama.enabled