# Workflow for validating Infrastructure as Code
name: Validate Infrastructure as Code

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    # Limit runs to only when opentofu changes
    paths:
      - "opentofu/**"
      - ".github/workflows/opentofu.yml"

  # Allows running this workflow manually
  workflow_dispatch:

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    # Block merging if the job fails
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          curl -sSL https://get.opentofu.org/install.sh | bash
          echo "$HOME/.opentofu/bin" >> $GITHUB_PATH

      - name: Initialize OpenTofu
        run: tofu init -backend=false

      - name: Validate OpenTofu code
        run: tofu validate

      - name: Validate OpenTofu formatting
        run: tofu fmt -recursive -check
